### ISSUE TITLE
最新mrubyでのC++の関係するリンクエラーについて。

### ISSUE THREAD

**Issue by t-wata-cldt** [dyama/mruby-siren#33]
https://twitter.com/dyama226/status/803414672909045760
を拝見しました。

どうやら、なんも考えずに入れられたこいつが原因っぽいです:
https://github.com/mruby/mruby/pull/3267

https://github.com/mruby/mruby/blob/2d335daeeb1d50402041041c7a3531674a2e735a/tasks/mrbgem_spec.rake#L151-L152
で`extern "C"`がC++でのみ追加されてないと死ぬっぽいです。
対策としては、gemの`extern "C"`を外すか、上近辺を修正するコードを本家に投げるかですね。

**Comment by t-wata-cldt** [comment]
影響範囲考えると https://github.com/mruby/mruby/pull/3267 はアレデスねー

**Comment by dyama** [comment]
ありがとうございます。こちらに気付かず[本家に issue](https://github.com/mruby/mruby/issues/3308) してしまいました。同じ絡みかな…、もう少しよく見てみます。

**Comment by dyama** [comment]
Fix with 1c15dad.
