### ISSUE TITLE
Compoundｸﾗｽのｲﾝｽﾀﾝｽ

### ISSUE THREAD

**Issue by kandennti** [dyama/mruby-siren#35]
こちらのバイナリ版を利用させていただいております。
https://github.com/dyama/mruby-siren/releases/tag/v0.13
ｖ0.12からｖ0.13で大きく変更が加えられたように感じております。

Compoundｸﾗｽのｲﾝｽﾀﾝｽですが、
`cmp = Siren.Compound.new`
かと思っているのですが、ｴﾗｰとなってしまいます。
(配列を渡しても同じでした)

どの様な記述をすれば良いのでしょうか?

**Comment by kandennti** [comment]
最終的なものをｴｸｽﾎﾟｰﾄする際に使用したかっただけの為
to_compﾒｿｯﾄﾞを利用する事にしました。

**Comment by dyama** [comment]
ありがとうございます。仕様が流動的に変化しており、すみません。

> Compoundｸﾗｽのｲﾝｽﾀﾝｽですが、
> cmp = Siren.Compound.new
> かと思っているのですが、ｴﾗｰとなってしまいます。

[リファレンスマニュアルの記事](https://github.com/dyama/mruby-siren/wiki/class-Compound)を参考にされたと思いますが、v0.13のWIndowsバイナリ版から[多くの変更](https://github.com/dyama/mruby-siren/compare/v0.13...master)が施されています。(記事は [master ](https://github.com/dyama/mruby-siren/tree/master) がターゲットです)

最新の master でWindowsバイナリを作成し公開しようと考えています。Open CASCADE 7.1.0 の MSYS2/MinGW64/CMake 環境でのビルドで少し躓いていますが、時間をみつけて通してみたいと思っています。それまでは

> to_compﾒｿｯﾄﾞを利用する事にしました。

でお願いします。

**Comment by dyama** [comment]
v0.14のドラフトバージョンの Windows バイナリを[リリースしました](https://github.com/dyama/mruby-siren/releases/tag/siren_0.14d)。正式リリースではないためサンプルスクリプトやビューア等は同梱していませんが、[現在のリファレンスマニュアルの記事内容](https://github.com/dyama/mruby-siren/wiki/Reference-manual)とほぼ一致しているはずです。よろしければご確認ください。

**Comment by kantoku-code** [comment]
dyama様


いつもありがとうございます。


Autodesk社のFusion360と言うCADをご存知でしょうか?

こちらのCADは非常に多くのフォーマットのCADデータを

インポートすることが可能なのですが、ｻｰﾌｪｽ・ｿﾘｯﾄﾞのみ

で点・線が欠落してしまいます。

https://forums.autodesk.com/t5/fusion-360-ri-ben-yu/igesrain-kabu-detanoinpoto/m-p/6606029#M3144

igesライン（カーブ）データのインポート<https://forums.autodesk.com/t5/fusion-360-ri-ben-yu/igesrain-kabu-detanoinpoto/m-p/6606029#M3144>
forums.autodesk.com
はじめまして。   他のCADで作成をした、３Dのカーブデータを読み込みたいのですが、 インポートの方法がわかりません。   どのようにすれば宜しいでしょうか？   よろしくお願いいたします。

https://forums.autodesk.com/t5/fusion-360-ri-ben-yu/stp-xing-shi-dengnofairuwo-dumi-rumi-shuki-chushiwo-xingtta-shini-dian-xiannadono-yao-suga-xiaoeteiru/m-p/7218766#M6156


Fusion360もAPIは、かなり公開されており、
http://help.autodesk.com/view/fusion360/ENU/?guid=GUID-dc7ae251-e060-4d87-b6b8-e7f78abc0777

これらの問題を "Sirenを利用すれば解決出来るのでは？"

と思ったのですが、素人レベルで可能なものか・・・

と感じております。


Siren自身の魅力は、バイナリ版であれば導入が非常に

簡単なため、多くのユーザーにも受け入れやすいもの

と感じているのですが、ｍRuby↔Python間でﾃﾞｰﾀの

やり取りが可能なものか？どうか？　もよくわからない

状態なのが正直なところです…。


Kantoku


________________________________
差出人: Daisuke YAMAGUCHI <notifications@github.com>
送信日時: 2017年8月4日 10:59
宛先: dyama/mruby-siren
CC: kantoku; Author
件名: Re: [dyama/mruby-siren] Compoundｸﾗｽのｲﾝｽﾀﾝｽ (#35)


v0.14のドラフトバージョンの Windows バイナリをリリースしました<https://github.com/dyama/mruby-siren/releases/tag/siren_0.14d>。正式リリースではないためサンプルスクリプトやビューア等は同梱していませんが、現在のリファレンスマニュアルの記事内容<https://github.com/dyama/mruby-siren/wiki/Reference-manual>とほぼ一致しているはずです。よろしければご確認ください。

**Comment by dyama** [comment]
@kandennti Compound の話ではないようですので、[新しい  Issue を作成](https://github.com/dyama/mruby-siren/issues/new)して同文を再投稿していただけますか？
お手数ですが、よろしくお願いします。
